### ISSUE TITLE
AUTOSAR schema version

### ISSUE THREAD

**Issue by toolsh** [girishchandranc/autosarfactory#8]
Hi girishchandranc,
This is really a good tool to read and write arxml.
Which AUTOSAR schema version is supported currently?
Is there a way to support different versions?
I use it to read an arxml of autosar-00048.xsd and get an error that PROCESS-DESIGN-TO-MACHINE-DESIGN-MAPPING-SET is not supported.
I would like to understand how autosarfactory.py is organized/coded so that I can make changes to let it support autosar-00048.xsd.

Thanks for your support.

**Comment by girishchandranc** [comment]
Hi toolsh,
Sorry for the delayed response as the email notification was in my spam and noticed the issue only while checking the github project now.

The autosarfactory only supports a single Autosar version(Autosar R22-11 schema 00051.xsd) at the moment. As you could already imagine, the python file is purely auto-generated so, making manual changes isn't a feasible solution. 
I think, supporting multiple Autosar versions is the best way to go. But, I am still figuring out how it could be incorporated. 

I could see that the model element "PROCESS-DESIGN-TO-MACHINE-DESIGN-MAPPING-SET" is removed since the Autosar version R21-11. Is that an element of interest to you? If so, then we should try supporting the schema corresponding to version below R21-11 so that you are not blocked from reading the file. But, if you are not interested in this element, then maybe removing it from the arxml file could also help.

Do you get errors for more elements? Can you please provide more details.
Thanks and Best Regards!

**Comment by Manchey** [comment]
Hi @girishchandranc ,
As you said " the python file is purely auto-generated", is there a tutorial / code about how to generated the python file? 
Is it generated from the Autosar schema file (e.g. AUTOSAR_00051.xsd) ?

Thanks for your support.

**Comment by girishchandranc** [comment]
Hi @Manchey ,
Sorry for the delayed response. Unfortunately, there isn't a guide to generate the python file. It's actually generated from another github project, which is unfortunately private since it doesn't meet the needed quality standards and all. 
So, there isn't a tutorial for it.

I intend to support multiple AR versions in future and so, probably, will provide an option to load the right model based on an argument which takes the AR version.

Sorry that isn't the response you were looking for.

On the other hands, could you please let me know why you need the model to be generated for a specific version? Just to understand.
Thanks!

**Comment by girishchandranc** [comment]
Closing ticket as no feedback yet.

**Comment by Manchey** [comment]
Hi @girishchandranc,
thanks for your reply and sorry for the dealyed response.

> On the other hands, could you please let me know why you need the model to be generated for a specific version? Just to understand.

I wanna use this package to parse my arxml file which is base on autosar R19-11, and there's some error happens which i think maybe due to the different autosar version.
And here's the traceback log just in case you are interested:
>Traceback (most recent call last):
  File ".\test.py", line 135, in parse_arxml
    root, status = autosarfactory.read([arxml_file])
  File "C:\ProgramData\Anaconda3\lib\site-packages\autosarfactory-0.2.3-py3.7.egg\autosarfactory\autosarfactory.py", line 42, in read
    status &= __read_file(file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autosarfactory-0.2.3-py3.7.egg\autosarfactory\autosarfactory.py", line 72, in __read_file
    asrRootNode = AUTOSAR()._build(tree.getroot(), file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autosarfactory-0.2.3-py3.7.egg\autosarfactory\autosarfactory.py", line 47448, in _build
    buildarPackages_node = ARPackage()._build(self, arPackages_node, file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autosarfactory-0.2.3-py3.7.egg\autosarfactory\autosarfactory.py", line 259743, in _build
    buildarPackages_node = ARPackage()._build(self, arPackages_node, file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autosarfactory-0.2.3-py3.7.egg\autosarfactory\autosarfactory.py", line 259733, in _build
    buildelements_node = __str_to_class__(elements_obj_dict[etree.QName(elements_node).localname])()._build(self, elements_node, file)
KeyError: 'TRANSFORMATION-PROPS-TO-SERVICE-INTERFACE-ELEMENT-MAPPING-SET'

**Comment by girishchandranc** [comment]
Hi @Manchey ,
I am happy to inform you that now there exists autosarfacrory corresponding to multiple Autosar versions ranging from Autosar 4.0.3 until R22-11.  So, in case if you are looking for specific version, you may find it in the folder autosar_releases. 

Thank you.
